civic_affordability:
  target: dev
  outputs:
    dev:
      type: postgres
      host: db.wtfcubbiyglhsywrbkgf.supabase.co
      user: postgres
      password: "{{ env_var('DBT_ENV_SECRET_PG_PASSWORD') }}"
      port: 5432
      dbname: postgres
      schema: analytics
      threads: 4
      connect_timeout: 10
      sslmode: require
