-- Grant read-only access for notebook role.
-- Replace placeholder before manual execution:
--   {{ROLE_NAME}}

GRANT USAGE ON SCHEMA analytics TO "{{ROLE_NAME}}";
GRANT USAGE ON SCHEMA raw TO "{{ROLE_NAME}}";

GRANT SELECT ON ALL TABLES IN SCHEMA analytics TO "{{ROLE_NAME}}";
GRANT SELECT ON ALL TABLES IN SCHEMA raw TO "{{ROLE_NAME}}";

GRANT SELECT ON ALL SEQUENCES IN SCHEMA analytics TO "{{ROLE_NAME}}";
GRANT SELECT ON ALL SEQUENCES IN SCHEMA raw TO "{{ROLE_NAME}}";

-- Ensure future objects remain readable.
ALTER DEFAULT PRIVILEGES IN SCHEMA analytics GRANT SELECT ON TABLES TO "{{ROLE_NAME}}";
ALTER DEFAULT PRIVILEGES IN SCHEMA raw GRANT SELECT ON TABLES TO "{{ROLE_NAME}}";

ALTER DEFAULT PRIVILEGES IN SCHEMA analytics GRANT SELECT ON SEQUENCES TO "{{ROLE_NAME}}";
ALTER DEFAULT PRIVILEGES IN SCHEMA raw GRANT SELECT ON SEQUENCES TO "{{ROLE_NAME}}";
